name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch
  workflow_dispatch:  # allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true  # caches gems between runs

      # 3. Install dependencies
      - name: Install dependencies
        run: bundle install

      # 4. Build Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # optional: keep history of previous deploys
          keep_files: false
